### ISSUE TITLE
Need help - getting started

### ISSUE THREAD

**Issue by azman0101** [debops/docs#143]
Hi,

I've just created a new project
debops-init ~/test_proj/

Then I've created a sshd.yml group_vars inventory file:
```
---

sshd_ferm_limit: 'false'
sshd_config_ports: [ '22', '2200' ]
ferm_input_list:
  - dport: [ '2200' ]
    accept_any: True
```
And then run debops
```
.
├── inventory
│   ├── group_vars
│   │   └── all
│   │       └── sshd.yml
│   ├── hosts
│   └── host_vars
├── playbooks
├── roles
└── secret
    ├── credentials
    │   └── debian
    │       └── console
    │           └── root
    │               └── password
```

I don't understand why the root password is change. Is this while bootstraping ?
Is this change by:
```
password: 'krypt pass'         # mkpasswd --method=SHA-512 oder cat /etc/shadow
```
So, How can I retreive it in plain text ?
```
TASK [debops.ferm : Remove iptables INPUT rules if requested] ******************
skipping: [cc_host] => (item={u'dport': [u'2200'], u'accept_any': True}) 
skipping: [pivot_host] => (item={u'dport': [u'2200'], u'accept_any': True}) 
```
Why this is skipped ?

I'm sorry for than question but it seems I miss something in the documentation...
