### ISSUE TITLE
Unified sections and Vim folds.

### ISSUE THREAD

**Issue by ypid** [debops/docs#156]
Proposal for new unified sections and Vim folds format:

```YAML
---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Default variables
# =================
#
# .. contents:: Sections
#    :local:
#
# .. include:: includes/all.rst

# Packages and installation [[[
# -------------------------

# .. envvar:: ROLE_NAME__base_packages
#
# List of base packages to install.
ROLE_NAME__base_packages:
  - 'ROLE_NAME'


# .. envvar:: ROLE_NAME__deploy_state
#
# What is the desired state which this role should achieve? Possible options:
#
# ``present``
#   Default. Ensure that `changeme/FIXME** is installed and configured as requested.
#
# ``absent``
#   Ensure that `changeme/FIXME** is uninstalled and it's configuration is removed.
#
ROLE_NAME__deploy_state: 'present'

# .. ]]]

# Another section [[[
# ---------------

# .. envvar:: ROLE_NAME__example
#
# Description.
ROLE_NAME__example: []

# .. ]]]
```

Refer to: https://github.com/htgoebel/yaml2rst/pull/3 and https://github.com/htgoebel/yaml2rst/blob/develop/docs/fold-markers.rst for details.
