### ISSUE TITLE
Create debops-contributors repo to keep track of contributors.

### ISSUE THREAD

**Issue by ypid** [debops/docs#157]
Proposing to create `debops/debops-contributors` repo which holds documentation about all contributors.

`The team` section from https://wiki.debops.org/about can be moved to the repo, having one section for each contributor with real name and short introduction. More info can be linked to.

With #155 in place, contributor nick names used throughout the docs can link to the section in `debops/debops-contributors`.

References can be made like this:

```reStructuredText

- Initial release. [drybjed_]
```

**Comment by drybjed** [comment]
I will create the initial repository tommorow with layout similar to the other "docs" sites, so that it can be included on the http://docs.debops.org/ website.

**Comment by ypid** [comment]
Another way would be to generate the contributor to real name mapping from `meta/ansigenome.yml`.

```YAML

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops/unattended_upgrades/'
  github_url: 'https://github.com/debops/ansible-unattended_upgrades'
  git_branch: 'master'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      url: 'http://ypid.de/'
      email: 'ypid@riseup.net'
      twitter: 'ypid'
      github: 'ypid'

```

So this could avoid having the `debops/debops-contributors` repo since the information is basically already bundled with the individual roles.
Script for that should be trivial.
